apps/dashboard/urls.py
from django.urls import path

from apps.worker.views import create_worker, list_worker
from apps.patient.views import create_patient, list_patient
from apps.blog.views import create_blog, list_blog
from apps.schedule.views import create_event, list_event, print_event
from .views import home, calendar


app_name = "dashboard"
urlpatterns = [

    path('administration/create_worker/', create_worker, name='create_worker'),
    path('administration/list_worker/', list_worker, name='list_worker'),
    path('administration/view_worker/<dni>', list_worker, name='list_worker'),

    path('administration/create_patient/', create_patient, name='create_patient'),
    path('administration/list_patient/', list_patient, name='list_patient'),
    path('administration/view_patient/<dni>', list_worker, name='list_patient'),

    path('schedule/', calendar, name='calendar'),
    path('schedule/create_event/', create_event, name='create_event'),
    path('schedule/list_event/', list_event, name='list_event'),
    path('schedule/print_event/<year>/<month>/<patient>', print_event, name='print_event'),

    path('blog/create-blog/', create_blog, name='create_blog'),
    path('blog/list-blog/', list_blog, name='list_blog'),
    path('blog/view-blog/<pk>', list_blog, name='list_blog'),

    path('', home, name='home'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.frontend.views import home, contact
from apps.worker.views import login, SignOutView

from django.conf.urls.i18n import i18n_patterns

admin.site.site_header = settings.SITE_HEADER
admin.site.site_title = settings.SITE_TITLE
admin.site.index_title = settings.INDEX_TITLE

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('summernote/', include('django_summernote.urls')),
    path('blog/', include('apps.blog.urls')),
    path('', home, name='home'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('login/', login, name='login'),
    path('logout/', SignOutView.as_view(), name='logout'),
    path('dashboard/', include('apps.dashboard.urls')),
    path('contact/', contact, name='contact'),
)

apps/dashboard/models.py
from django.db import models

# Create your models here.

apps/dashboard/views.py
from django.utils import timezone


from django.shortcuts import render
from django.utils.translation import gettext_lazy as _

from apps.schedule.models import Event


def home(request):
    worker_events = ''
    if request.user.is_staff:
        context = {

        }
        return render(request, 'dashboard/dashboard_admin.html', context)

    try:
        worker_events = Event.objects.filter(worker__user__username=request.user.username)
    except Event.DoesNotExist:
        worker_events = ''

    context = {
        'worker_events': worker_events,
    }

    return render(request, 'dashboard/dashboard_worker.html', context)


def calendar(request):
    try:
        items = Event.objects.all()
    except Event.DoesNotExist:
        items = ''

    context = {
        'items': items,
        'month': _('month')
    }

    return render(request, 'dashboard/view/calendar_list.html', context)

templates/dashboard/_header_menu.html
{% load i18n %}

<button class="kt-header-menu-wrapper-close" id="kt_header_menu_mobile_close_btn"><i class="la la-close"></i></button>
<div class="kt-header-menu-wrapper" id="kt_header_menu_wrapper">
    <div id="kt_header_menu" class="kt-header-menu kt-header-menu-mobile ">
        <ul class="kt-menu__nav ">
            <li class="kt-menu__item  kt-menu__item--open kt-menu__item--here kt-menu__item--submenu kt-menu__item--rel kt-menu__item--open kt-menu__item--here" data-ktmenu-submenu-toggle="click" aria-haspopup="true"><a href="" class="kt-menu__link kt-menu__toggle"><span class="kt-menu__link-text">{% trans "dashboard"|capfirst %}</span><i class="kt-menu__ver-arrow la la-angle-right"></i></a>
            </li>
            {% include "block/_block_links.html" with node=dash hook='hd' %}
        </ul>
    </div>
    <div class="kt-header-toolbar">
        <div class="kt-quick-search" id="kt_quick_search_default">
            <form method="get" class="kt-quick-search__form">
                <div class="input-group">
                    <div class="input-group-prepend"><span class="input-group-text"><i class="flaticon2-search-1"></i></span></div>
                    <input type="text" class="form-control kt-quick-search__input" placeholder="{% trans 'search'|capfirst %}...">
                    <div class="input-group-append"><span class="input-group-text"><i class="la la-close kt-quick-search__close"></i></span></div>
                </div>
            </form>
            <div id="kt_quick_search_toggle" data-toggle="dropdown" data-offset="0px,10px"></div>
            <div class="dropdown-menu dropdown-menu-fit dropdown-menu-right dropdown-menu-anim dropdown-menu-lg">
                <div class="kt-quick-search__wrapper kt-scroll" data-scroll="true" data-height="300" data-mobile-height="200">
                </div>
            </div>
        </div>
    </div>
</div>

templates/dashboard/_language_selector.html
{% load static %}
{% load i18n %}
<div class="kt-header__topbar-wrapper" data-toggle="dropdown" data-offset="10px,10px">
    {% get_current_language as LC%}
    {% if LC == 'es'%}
        <span class="kt-header__topbar-icon">
            <img class="" src="{% static 'dashboard/media/flags/016-spain.svg' %}" alt="spain" />
        </span>
    {% endif %}
    {% comment %}
    {% if LC == 'en'%}
        <span class="kt-header__topbar-icon">
            <img class="" src="{% static 'dashboard/media/flags/012-uk.svg' %}" alt="uk" />
        </span>
    {% endif %}
    {% endcomment %}
    {% if LC == 'pt'%}
        <span class="kt-header__topbar-icon">
            <img class="" src="{% static 'dashboard/media/flags/005-portugal.svg' %}" alt="portugal" />
        </span>
    {% endif %}
    {% if LC == 'gl'%}
        <span class="kt-header__topbar-icon">
            <img class="" src="{% static 'dashboard/media/flags/021-galician.svg' %}" alt="galician" />
        </span>
    {% endif %}
</div>
<div class="dropdown-menu dropdown-menu-fit dropdown-menu-right dropdown-menu-anim">
    <ul class="kt-nav kt-margin-t-10 kt-margin-b-10">
        <li class="kt-nav__item kt-nav__item--active">
            <a href="/pt/dashboard/" class="kt-nav__link">
                <span class="kt-nav__link-icon"><img src="{% static 'dashboard/media/flags/005-portugal.svg' %}" alt="portugal" /></span>
                <span class="kt-nav__link-text">{% trans "portuguese"|title %}</span>
            </a>
        </li>
        <li class="kt-nav__item">
            <a href="/es/dashboard/" class="kt-nav__link">
                <span class="kt-nav__link-icon"><img src="{% static 'dashboard/media/flags/016-spain.svg' %}" alt="spain" /></span>
                <span class="kt-nav__link-text">{% trans "spanish"|title %}</span>
            </a>
        </li>
        <li class="kt-nav__item">
            <a href="/gl/dashboard/" class="kt-nav__link">
                <span class="kt-nav__link-icon"><img src="{% static 'dashboard/media/flags/021-galician.svg' %}" alt="galician" /></span>
                <span class="kt-nav__link-text">{% trans "galician"|title %}</span>
            </a>
        </li>
        {% comment %}
        <li class="kt-nav__item">
            <a href="/en/dashboard/" class="kt-nav__link">
                <span class="kt-nav__link-icon"><img src="{% static 'dashboard/media/flags/012-uk.svg' %}" alt="uk" /></span>
                <span class="kt-nav__link-text">{% trans "english"|title %}</span>
            </a>
        </li>
        {% endcomment %}
    </ul>
</div>

templates/dashboard/_user_topbar_menu.html
{% load i18n %}
{% load static %}
<div class="kt-header__topbar-wrapper" data-toggle="dropdown" data-offset="10px,10px" aria-expanded="false">
<span class="kt-header__topbar-welcome">{% trans "hi" %},</span>
<span class="kt-header__topbar-username">{{ request.user.first_name|title|default:'user' }}</span>
<img class="kt-hidden" alt="Pic" src="{{ request.user.worker.image.url }}">

<!--use below badge element instead the user avatar to display username's first letter(remove kt-hidden class to display it) -->
<span class="kt-badge kt-badge--username kt-badge--unified-success kt-badge--lg kt-badge--rounded kt-badge--bold kt-hidden-">{{ request.user.first_name|make_list|first|title|default:'u' }}</span>
</div>
<div class="dropdown-menu dropdown-menu-fit dropdown-menu-right dropdown-menu-anim dropdown-menu-xl">

<!--begin: Head -->
<div class="kt-user-card kt-user-card--skin-dark kt-notification-item-padding-x" style="background-image: url({% static 'dashboard/media/misc/bg-1.jpg' %})">
    <div class="kt-user-card__avatar">
        <img alt="Pic" src="{% if request.user.is_staff %}/media/worker/yisus.jfif {% else %}{{ request.user.worker.image.url }}{% endif %}" />
        <!--use below badge element instead the user avatar to display username's first letter(remove kt-hidden class to display it) -->
        {% comment %}
        <span class="kt-badge kt-badge--lg kt-badge--rounded kt-badge--bold kt-font-success">{{ request.user.username|title }}</span>
        {% endcomment %}
    </div>
    <div class="kt-user-card__name">
        {{ request.user.get_full_name|title|default:'user' }}
    </div>
    <div class="kt-user-card__badge">
        <span class="btn btn-success btn-sm btn-bold btn-font-md">
            {% if request.user.is_staff %}
                {% trans "admin"|capfirst %}
            {% else %}
                {% trans "worker"|capfirst %}
            {% endif %}
        </span>
    </div>
</div>

<!--end: Head -->

<!--begin: Navigation -->
<div class="kt-notification">
    <a href="" class="kt-notification__item">
        <div class="kt-notification__item-icon">
            <i class="flaticon2-calendar-3 kt-font-success"></i>
        </div>
        <div class="kt-notification__item-details">
            <div class="kt-notification__item-title kt-font-bold">
                {% trans "my profile"|title %}
            </div>
            <div class="kt-notification__item-time">
                {% trans "account settings and more"|capfirst %}
            </div>
        </div>
    </a>
    {% comment %}

    <a href="#" class="kt-notification__item">
        <div class="kt-notification__item-icon">
            <i class="flaticon2-mail kt-font-warning"></i>
        </div>
        <div class="kt-notification__item-details">
            <div class="kt-notification__item-title kt-font-bold">
                My Messages
            </div>
            <div class="kt-notification__item-time">
                Inbox and tasks
            </div>
        </div>
    </a>
    <a href="#" class="kt-notification__item">
        <div class="kt-notification__item-icon">
            <i class="flaticon2-rocket-1 kt-font-danger"></i>
        </div>
        <div class="kt-notification__item-details">
            <div class="kt-notification__item-title kt-font-bold">
                My Activities
            </div>
            <div class="kt-notification__item-time">
                Logs and notifications
            </div>
        </div>
    </a>
    <a href="#" class="kt-notification__item">
        <div class="kt-notification__item-icon">
            <i class="flaticon2-hourglass kt-font-brand"></i>
        </div>
        <div class="kt-notification__item-details">
            <div class="kt-notification__item-title kt-font-bold">
                My Tasks
            </div>
            <div class="kt-notification__item-time">
                latest tasks and projects
            </div>
        </div>
    </a>
    <a href="#" class="kt-notification__item">
        <div class="kt-notification__item-icon">
            <i class="flaticon2-cardiogram kt-font-warning"></i>
        </div>
        <div class="kt-notification__item-details">
            <div class="kt-notification__item-title kt-font-bold">
                Billing
            </div>
            <div class="kt-notification__item-time">
                billing & statements <span class="kt-badge kt-badge--danger kt-badge--inline kt-badge--pill kt-badge--rounded">2 pending</span>
            </div>
        </div>
    </a>
    {% endcomment %}
    <div class="kt-notification__custom kt-space-between">
        <a href="{% url 'logout' %}" target="_blank" class="btn btn-label btn-label-brand btn-sm btn-bold">{% trans "sign out" %}</a>
        {% comment %}
            <a href="demo2/custom/user/login-v2.html" target="_blank" class="btn btn-clean btn-sm btn-bold">Upgrade Plan</a>
        {% endcomment %}
    </div>
</div>

<!--end: Navigation -->
</div>

templates/dashboard/footer.html
{% load static %}

<div class="kt-footer  kt-footer--extended  kt-grid__item" id="kt_footer">
    {% comment %}
    <div class="kt-footer__top">
        <div class="kt-container ">
            <div class="row">
                <div class="col-lg-4">
                    <div class="kt-footer__section">
                        <h3 class="kt-footer__title">About</h3>
                        <div class="kt-footer__content">
                            Whatever method you chosse,these nine will
                            make you re-think theway you craft healines
                            Why? Because they all have points in that are
                            worth from a point of view.
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="kt-footer__section">
                        <h3 class="kt-footer__title">Quick Links</h3>
                        <div class="kt-footer__content">
                            <div class="kt-footer__nav">
                                <div class="kt-footer__nav-section">
                                    <a href="#">General Reports</a>
                                    <a href="#">Dashboart Widgets</a>
                                    <a href="#">Custom Pages</a>
                                </div>
                                <div class="kt-footer__nav-section">
                                    <a href="#">User Setting</a>
                                    <a href="#">Custom Pages</a>
                                    <a href="#">Intranet Settings</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="kt-footer__section">
                        <h3 class="kt-footer__title">Get In Touch</h3>
                        <div class="kt-footer__content">
                            <form action="" class="kt-footer__subscribe">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Enter Your Email">
                                    <div class="input-group-append">
                                        <button class="btn btn-brand" type="button">Join</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endcomment %}
    <div class="kt-footer__bottom">
        <div class="kt-container ">
            <div class="kt-footer__wrapper">
                <div class="kt-footer__logo">
                    <a href="{% url 'dashboard:home' %}">
                        <img alt="Logo" src="{% static 'img/logo.svg' %}" data-retina="true" alt="" width="100" height="36">
                    </a>
                    <div class="kt-footer__copyright">
                        {% now "Y" %}
                        <a href="http://keenthemes.com/metronic" target="_blank">{{ app_name|title }}</a>
                    </div>
                </div>

                <div class="kt-footer__menu">
                {% comment %}
                    <a href="http://keenthemes.com/metronic" target="_blank">Purchase Lisence</a>
                    <a href="http://keenthemes.com/metronic" target="_blank">Team</a>
                    <a href="http://keenthemes.com/metronic" target="_blank">Contact</a>
                {% endcomment %}
                </div>
            </div>
        </div>
    </div>
</div>